function panel = addStackPanel(this, stack)
%ADDSTACKPANEL
    parent = this.handles.innerStackContainer;
    panel = handle(uipanel( ...
        'Parent', parent, ...
        'BackgroundColor', parent.BackgroundColor, ...
        'Units', 'Pixels', ...
        'HandleVisibility', 'off', ...
        'BorderWidth', 0, ...
        'Position', [0, 0, 30, 30]...
    ));
    addlistener(panel, 'SizeChanged', @arrange);
    addlistener(panel, 'BackgroundColor', 'PostSet', @propagateColor);
    
    name = handle(uicontrol( ...
        'Parent', panel, ...
        'Style', 'text', ...
        'BackgroundColor', panel.BackgroundColor, ...
        'HandleVisibility', 'off', ...
        'String', stack.char(), ...
        'HorizontalAlignment', 'left' ...
    ));
    
    inspectButton = handle(uicontrol( ...
        'Parent', panel, ...
        'Style', 'pushbutton', ...
        'HandleVisibility', 'off', ...
        'String', 'inspect', ...
        'Callback', @(~,~)stack.dialog() ...
    ));
    
    decorateButton = handle(uicontrol( ...
        'Parent', panel, ...
        'Style', 'pushbutton', ...
        'HandleVisibility', 'off', ...
        'String', 'decorate', ...
        'Callback', @(~,~)this.addStack(TiffStackDecorator.guiAddDecorator(stack)) ...
    ));
    
    removeButton = handle(uicontrol( ...
        'Parent', panel, ...
        'Style', 'pushbutton', ...
        ...'BackgroundColor', panel.BackgroundColor, ...
        'HandleVisibility', 'off', ...
        'String', '-', ...
        'Callback', @(~,~)this.removeStack(stack) ...
    ));
    
    function arrange(~,~)
        pos = panel.Position;
        name.Position = [ ...
            5, ...
            5, ...
            pos(3) - 10, ...
            pos(4) - 10 ...
        ];
        
        buttonHeight = 20;
        buttonY = (pos(4) - buttonHeight) / 2;
        
        inspectButton.Position = [ ...
            pos(3) - 5 - 20 - 5 - 50 - 5 - 50, ...
            buttonY, ...
            50, ...
            buttonHeight ...
        ];
        
        decorateButton.Position = [ ...
            pos(3) - 5 - 20 - 5 - 50, ...
            buttonY, ...
            50, ...
            buttonHeight ...
        ];
        
        removeButton.Position = [ ...
            pos(3) - 5 - 20, ...
            buttonY, ...
            20, ...
            buttonHeight ...
        ];
    end
    function propagateColor(~,~)
        name.BackgroundColor = panel.BackgroundColor;
%         removeButton.BackgroundColor = panel.BackgroundColor;
    end
end

