function fit = gammaDistribution()
%GAMMADISTRIBUTION creates fit object fro a gamma distribution
    
%     fit = Fit.FitObject(@(a, mu, var, x) ...
%         a ...
%         .* (mu./var).^(mu.^2./var) ...
%         ./ gamma(mu.^2./var) ...
%         .*x.^(mu.^2./var-1).*exp(-(mu./var).*x));
    fit = Fit.FitObject(@(a, mu, var, x) ...
        a ...
        .* gampdf(x, mu.^2./var, var./mu) ...
    );
    
    fit.funcTex = '$\Gamma(x, \frac{\mu^2}{var}, \frac{var}{\mu}$)';%'$a \cdot x^{\mu/\beta-1}\cdot e^{-x/\beta}$';
    fit.setArgumentValue( ...
        {'a', 'mu', 'var'}, ...
        [1, 10, 10] ...
    );
end

