function fit = gaussSymmetric2D()
%EXPONENTIAL creates a exponential fit object
    
    fit = Fit.FitObject( ...
        @(mu1, mu2, sigma, a, b, x1, x2) ...
            a .* exp( ...
                -1/2.*((x1-mu1)./sigma).^2 ...
                -1/2.*((x2-mu2)./sigma).^2 ...
            ) + b ...
    );
    
    fit.setIndependent('x1');
    fit.setIndependent('x2');
    fit.setArgumentValue( ...
        {'mu1', 'mu2', 'sigma', 'a', 'b'}, ...
        [0, 0, 1, 1, 0] ...
    );
end