function str = char(this)
%CHAR cast function to char
    
    str = sprintf( ...
        '%s<(%d-%d)x(%d-%d) of %s>', ...
        class(this), ...
        this.xRange(1), ...
        this.xRange(2), ...
        this.yRange(1), ...
        this.yRange(2), ...
        this.stack.char() ...
    );
end

