function str = char(stack)
%CHAR cast function to char
    
    str = sprintf( ...
        '%s<(%d-%d)x(%d-%d) of %s>', ...
        class(stack), ...
        stack.xRange(1), ...
        stack.xRange(2), ...
        stack.yRange(1), ...
        stack.yRange(2), ...
        stack.stack.char() ...
    );
end

