function [panel, getParameter] = getGUIParameterPanel(parent)
    
    panel = handle(uipanel( ...
        'Parent', parent, ...
        'BackgroundColor', get(parent, 'Color'), ...
        'Units', 'pixels', ...
        'BorderWidth', 0, ...
        'HandleVisibility', 'off' ...
    ));

    getParameter = @readParameter;
    function param = readParameter()
        param = {};
    end
end

