function [panel, getParameter] = getGUIParameterPanel(parent)
    lowDefault = 2;
    highDefault = 20;
    
    panel = handle(uipanel( ...
        'Parent', parent, ...
        'BackgroundColor', get(parent, 'Color'), ...
        'Units', 'pixels', ...
        'BorderWidth', 0, ...
        'HandleVisibility', 'off' ...
    ));

    lowCutOffText = handle(uicontrol( ...
        'Parent', panel, ...
        'Style', 'text', ...
        'String', 'low cut off', ...
        'HandleVisibility', 'off' ...
    ));
    lowCutOffInput = handle(uicontrol( ...
        'Parent', panel, ...
        'Style', 'slider', ...
        'Min', 0, ...
        'Value', lowDefault, ...
        'Max', highDefault, ...
        'SliderStep', [0.01, 0.1], ...
        'HandleVisibility', 'off' ...
    ));
    Gui.addSliderContextMenu(lowCutOffInput);

    highCutOffText = handle(uicontrol( ...
        'Parent', panel, ...
        'Style', 'text', ...
        'String', 'high cut off', ...
        'HandleVisibility', 'off' ...
    ));
    highCutOffInput = handle(uicontrol( ...
        'Parent', panel, ...
        'Style', 'slider', ...
        'Min', 0, ...
        'Value', highDefault, ...
        'Max', 100, ...
        'SliderStep', [0.01, 0.1], ...
        'HandleVisibility', 'off' ...
    ));
    Gui.addSliderContextMenu(highCutOffInput);

    addlistener(panel, 'SizeChanged', @arrange);

    getParameter = @readParameter;
    function arrange(~,~)
        pos = panel.Position;
        lineHeight = (pos(4) - 5) / 2;
        textWidth = 80;
        controlWidth = pos(3) - textWidth - 5;
        lowCutOffText.Position = [0, lineHeight + 5, textWidth, lineHeight];
        lowCutOffInput.Position = [textWidth + 5, lineHeight + 5, controlWidth, lineHeight];
        highCutOffText.Position = [0, 0, textWidth, lineHeight];
        highCutOffInput.Position = [textWidth + 5, 0, controlWidth, lineHeight];
    end
    function param = readParameter()
        param = {[ ...
            lowCutOffInput.Value, ...
            highCutOffInput.Value ...
        ]};
    end
end

