function croppedStack = guiCrop(stack, title)
    if (nargin < 2)
        title = [];
    end
    dm = DialogManager(stack);
    dm.open(title);
    
    dm.addPanel();
    display = TiffStackDisplay(dm.currentPanel, stack, 1);
    dm.addPanel(1);
    display.createIndexSlider(dm);
    dm.show();
    
    position = [1, 1, stack.width, stack.height];
    rect = imrect(display.axes, position);
    setPositionConstraintFcn( ...
        rect, ...
        makeConstrainToRectFcn( ...
            'imrect', ...
            [1, stack.width], ...
            [1, stack.height] ...
        ) ...
    );
    addNewPositionCallback(rect, @updatePosition);
    
    dm.wait();
    croppedStack = CroppedTiffStack( ...
        stack, ...
        position(1) + [1, position(3)] - 1, ...
        position(2) + [1, position(4)] - 1 ...
    );
    function updatePosition(p)
        position = p;
    end
end