function handles = createHandles(input, varargin)
    handles.container = uicontainer(varargin{:});
    handles.pathDisplay = uicontrol( ...
        'Parent', handles.container, ...
        'Style', 'text', ...
        'BackgroundColor', get(handle.container, 'BackgroundColor'), ...
        'String', '' ...
    );
    
    handles.selectButton = uicontrol( ...
        'Parent', handles.container, ...
        'Style', 'pushbutton', ...
        'String', '...' ...
    );
end