function createHandles(obj, varargin)
%CREATEHANDLES creates the handles for the ImageDisplay
    obj.handles = struct();
    
    obj.handles.container = uicontainer( ...
        varargin{:} ...
    );
    
    addlistener(obj.handles.container, 'ObjectBeingDestroyed', @(~,~)delete(obj));

    obj.handles.contextMenu = uicontextmenu();
    uimenu(obj.handles.contextMenu, ...
        'Label', 'set color map', ...
        'Callback', @(~,~)obj.guiSetColormap() ...
    );
    uimenu(obj.handles.contextMenu, 'Label', 'set color scaling');
    obj.handles.axes = axes( ...
        'Parent', obj.handles.container, ...
        'GridLineStyle', 'none', ...
        'HandleVisibility', 'off', ...
        'PlotBoxAspectRatio', [1 1 1], ...
        'UIContextMenu', obj.handles.contextMenu, ...
        'XTick', [], ...
        'YTick', [] ...
    );

end

