function guiSetColormap(obj)
%GUISETCOLORMAP opens a GUI window to choose the color map
    colormaps = {'---', ...
        'gray', 'jet', 'hsv', 'hot', 'cool', ...
        'spring', 'summer', 'autumn', 'winter', ...
        'bone', 'copper', 'pink', 'lines'};
    
    f = figure( ...
        'HandleVisibility', 'off', ...
        'DockControls', 'off', ...
        'MenuBar', 'none', ...
        'Resize', 'off', ...
        'ToolBar', 'none', ...
        'Position', [200 200 100 20] ...
    );

    select = uicontrol( ...
        'Parent', f, ...
        'Style', 'popupmenu', ...
        'String', colormaps, ...
        'Callback', @selectCallback, ...
        'Units', 'Normalized', ...
        'Position', [0 0 1 1] ...
    );
    
    destroyListener = addlistener(obj, ...
        'ObjectBeingDestroyed', @objectDeleteHandler);
    addlistener(f, 'ObjectBeingDestroyed', @figureDeleteHandler);
    
    function selectCallback(varargin)
        value = get(select, 'Value');
        if (value ~= 1)
            obj.colormap = colormaps{value};
        end
    end
    
    function objectDeleteHandler(varargin)
        delete(f);
    end

    function figureDeleteHandler(varargin)
        delete(destroyListener);
    end
end

