function [panel, getParameter] = getGUIParameterPanel(parent, file)
    panel = handle(uipanel( ...
        'Parent', parent, ...
        'BackgroundColor', get(parent, 'Color'), ...
        'BorderWidth', 0, ...
        'Units', 'pixels', ...
        'HandleVisibility', 'off' ...
    ));

    schemaText = handle(uicontrol( ...
        'Parent', panel, ...
        'BackgroundColor', panel.BackgroundColor, ...
        'Style', 'text', ...
        'String', 'schema', ...
        'TooltipString', 'input for sprintf', ...
        'HandleVisibility', 'off' ...
    ));
    schemaInput = handle(uicontrol( ...
        'Parent', panel, ...
        'Style', 'edit', ...
        'String', file.filename, ...
        'HandleVisibility', 'off' ...
    ));

    filesText = handle(uicontrol( ...
        'Parent', panel, ...
        'BackgroundColor', panel.BackgroundColor, ...
        'Style', 'text', ...
        'String', ', ', ...
        'HandleVisibility', 'off' ...
    ));
    filesInput = handle(uicontrol( ...
        'Parent', panel, ...
        'Style', 'edit', ...
        'String', '[1:1]', ...
        'HandleVisibility', 'off' ...
    ));

    addlistener(panel, 'SizeChange', @arrange);

    getParameter = @readParameter;
    function arrange(~,~)
        pos = panel.Position;
        lineHeight = pos(4);
        textWidth = 40;
        controlWidth = (pos(3) - 2*textWidth - 3*5)/2;
        schemaText.Position = [0, 0, textWidth, lineHeight];
        schemaInput.Position = [textWidth + 5, 0, controlWidth, lineHeight];
        filesText.Position = [textWidth + 5 + controlWidth + 5, 0, textWidth, lineHeight];
        filesInput.Position = [textWidth + 5 + controlWidth + 5 + textWidth + 5, 0, controlWidth, lineHeight];
    end
    function param = readParameter()
        param = { ...
            file,...
            schemaInput.String, ...
            eval(filesInput.String) ...
        };
    end
end
   