function [panel, getParameter] = getGUIParameterPanel(parent, file)
    panel = handle(uipanel( ...
        'Parent', parent, ...
        'BackgroundColor', get(parent, 'Color'), ...
        'BorderWidth', 0, ...
        'Units', 'pixels', ...
        'HandleVisibility', 'off' ...
    ));

    getParameter = @readParameter;
    function param = readParameter()
        param = {file};
    end
end
   