function panel = addEntryPanel(this, entry)
%ADDENTRYPANEL adds a panel for the entry
    parent = this.handles.innerContainer;
    panel = handle(uipanel( ...
        'Parent', parent, ...
        'BackgroundColor', parent.BackgroundColor, ...
        'Units', 'Pixels', ...
        'HandleVisibility', 'off', ...
        'BorderWidth', 0, ...
        'Position', [0, 0, 30, 30]...
    ));
    this.fillEntryPanel(entry, panel);
end

