function header = createHeader(this)
    header = handle(uipanel( ...
        'Parent', this.handles.mainPanel, ...
        'Units', 'pixels', ...
        'BackgroundColor', this.handles.mainPanel.BackgroundColor, ...
        'HandleVisibility', 'callback', ...
        'BorderWidth', 0 ...
    ));
    try
        addlistener(header, 'SizeChanged', @arrange);
    catch
        addlistener(header, 'SizeChange', @arrange);
    end

    text = handle(uicontrol( ...
        'Parent', header, ...
        'HandleVisibility', 'off', ...
        'BackgroundColor', header.BackgroundColor, ...
        'Style', 'text', ...
        'String', this.contentName, ...
        'HorizontalAlignment', 'left' ...
    ));
    addEntry = handle(uicontrol( ...
        'Parent', header, ...
        'HandleVisibility', 'off', ...
        'Style', 'pushbutton', ...
        'String', '+', ...
        'Callback', @(~,~)this.addEntry(this.createEntry()) ...
    ));

    for el = [header, text]
        Gui.bindBackgroundColorToParent(el);
    end

    function arrange(~,~)
        pos = header.Position;
        text.Position = [5, 5, pos(3) - 10, pos(4) - 10];

        addEntry.Position = [ ...
            pos(3) - 25, ...
            (pos(4) - 20 ) / 2, ...
            20, ...
            20 ...
        ];
    end
end
