function ax = getAxes(f, varargin)
%GETAXES creates an axes object apropriate for the paper
    if (nargin < 1)
        f = Paper.getFigure();
    end
    
    ax = axes( ...
        varargin{:}, ...
        'FontName', 'Arial', ...
        'FontSize', 14, ...20, ...
        'TickDir', 'in', ...
        'Box', 'on', ...
        ...'Units', 'normalized', ...
        ...'OuterPosition', [0 0 1 1], ...
        'Parent', f ...
    );
end

