function f = getFigure(varargin)
%GETFIGURE opens a figure apropriate for the paper
    f = figure( ...
        varargin{:}, ...
        'NextPlot', 'new', ...
        ...'Units', 'pixels', ...
        ...'Position', [200 300 600 600*0.618], ...
        ...'PaperUnits', 'centimeter', ...
        ...'PaperSize', [16 16*0.618], ...
        'Color', 'w' ...
    );

end

