function h = legend(a, varargin)
%AXES.LEGEND usage like normal legend - just some formating stuff
    h = legend(a.ax, varargin{:});
    set( ...
        h, ...
        'FontSize', 12, ...
        'Box', 'off' ...
    );

end

