function setLogX(a)
%AXES.SETLOGX set x scale to logaritmic
    set(a.ax, ...
        'XScale', 'log' ...
    );
    set(a.ax, ...
        'XTickLabel', cellfun( ...
            @num2str, num2cell(get(a.ax, 'XTick')'), ...
            'UniformOutput', false ...
        ), ...
        'XTickLabelMode', 'manual', ...
        'XTickMode', 'manual' ...
    );

end

