function setLogY(a)
%AXES.SETLOGY set y scale to logaritmic
    set(a.ax, ...
        'YScale', 'log' ...
    );
    set(a.ax, ...
        'YTickLabel', cellfun( ...
            @num2str, num2cell(get(a.ax, 'YTick')'), ...
            'UniformOutput', false ...
        ), ...
        'YTickLabelMode', 'manual', ...
        'YTickMode', 'manual' ...
    );

end