f = figure(100);
a = axes('Parent', f);
plot(rand(100, 4), 'Parent', a);
api = Gui.verticalMarker( ...
    a, ...
    'Parent', f, ...
    'ValueInput', 'on', ...
    'MinInput', 'on', ...
    'MaxInput', 'on', ...
    'Value', 50, ...
    'Position', [1 1 500 40], ...
    'Color', 'red' ...
);
drawnow expose;
Gui.maximizeFigure(f);
% addlistener(api, 'valueChange', @(~,~)disp(api.value));
% addlistener(api, 'minChange', @(~,~)disp(api.min));
% addlistener(api, 'maxChange', @(~,~)disp(api.max));