function ax = overviewPlot(obj)
%OVERVIEWPLOT generates a plot for overview
    for o = obj
        ax = Paper.Axes();
        ax.plot( ...
            o.time, [o.value o.baselineCorrection o.baselineCorrectedValue o.filteredValue], '-', ...
            o.peakTimes, o.peakValues, 'x' ...
        );
        ax.legend( ...
            {'original', 'baseline', 'baseline corrected', 'filtered', 'peaks'} ...
        );
        ax.title(o.advancedName);
    end
end

