function [panel, getParameter] = getGUIParameterPanel(parent)
    
    panel = handle(uipanel( ...
        'Parent', parent, ...
        'BackgroundColor', get(parent, 'Color'), ...
        'Units', 'pixels', ...
        'BorderWidth', 0, ...
        'HandleVisibility', 'off' ...
    ));
    
    functionStrings = { ...
        'max - abs(image - median)', ...
        'max - image' ...
    };
    functions = { ...
        @FunctionTiffStack.medianBased, ...
        @FunctionTiffStack.inverted ...
    };

    funcInput = handle(uicontrol( ...
        'Parent', panel, ...
        'HandleVisibility', 'off', ...
        'Style', 'popupmenu', ...
        'String', functionStrings, ...
        'Value', 1 ...
    ));

    try
        addlistener(panel, 'SizeChanged', @arrange);
    catch
        addlistener(panel, 'SizeChange', @arrange);
    end

    function arrange(~,~)
        pos = panel.Position;
        lineHeight = (pos(4) - 5);
        controlWidth = pos(3) - 5;
        funcInput.Position = [5, 5, controlWidth, lineHeight];
    end
    getParameter = @readParameter;
    function param = readParameter()
        param = functions(funcInput.Value);
    end
end

